### ISSUE TITLE
Code doesn't work as is

### ISSUE THREAD

**Issue by DoriansGrave** [learn-co-curriculum/sinatra-nested-forms-readme#15]
I had to change the "class" iteration token to "course" because the former was registering as the class object. I made the changes to the readme file in master repo as well.
<img width="1440" alt="screen shot 2017-06-30 at 12 12 07 pm" src="https://user-images.githubusercontent.com/26909418/27746720-e7033ef8-5d8d-11e7-9a27-90c046a8bbc3.png">

**Comment by bperl** [comment]
Confirming that this is a problem since 'class' is a reserved keyword in Ruby.

**Comment by gj** [comment]
Fixed in #12 and #17. Thanks @DoriansGrave !
