### ISSUE TITLE
Describe initial hash build

### ISSUE THREAD

**Issue by michaelwahlin** [learn-co-curriculum/sinatra-nested-forms-readme#18]
**Currently**
my_hash["student"] = {}
my_hash["student"]["name"] = "Joe"

**Instead describe initial hash build to be explicit:**
my_hash = {}
my_hash["student"] = {}
my_hash["student"]["name"] = "Joe"

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
