### ISSUE TITLE
This is not a lab

### ISSUE THREAD

**Issue by rogercodes1** [learn-co-curriculum/sinatra-nested-forms-readme#21]
Should it be changed to a read me?

**Comment by maxwellbenton** [comment]
Thank you for providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
