### ISSUE TITLE
Looked like a read-only lesson but has a Fork option?

### ISSUE THREAD

**Issue by Cfrank482** [learn-co-curriculum/sinatra-nested-forms-readme#22]
I forked the repo in the sandbox and it still didnt mark the repo as forked. Im not sure what happened there.

**Comment by drakeltheryuujin** [comment]
Hi @Cfrank482!

This is a README, but if Learn is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please re-open this issue, provide any additional information you can, and we will try to discern a proper path to resolution.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
