### ISSUE TITLE
Some comments about the spec file

### ISSUE THREAD

**Issue by EvanPavley** [learn-co-curriculum/sinatra-nested-forms-readme#26]
I have some suggestions for making this spec more doable instead of getting stuck on syntax errors like I noticed some of my classmates were.

For this lesson,
the index.erb has "<a href="/new">Click Here To List A Puppy</a>" in it 
and the spec has "expect(page).to have_link("List a Puppy")"
so it fails the test because of the case of "A" that was given in the index.erb

the spec has "describe 'POST / do"
when it would make more sense if it was "describe 'POST /puppy do" because you enter the path in app.rb as "post '/puppy' do"

the spec also has "expect(page).to have_text(/Age:\s+6 months/i)"
with no mention of putting the word "months" at the end of the age in the readme
and the display_puppy.rb has "<p>Puppy Age: <%= @age %></p>" already in it
maybe it should be "<p>Puppy Age: <%= @age %> months</p>"

**Comment by drakeltheryuujin** [comment]
This issue is being closed now as it is off-topic for this lesson. I will address this on the lab it was meant for. Thanks! 💙
