### ISSUE TITLE
Wrong Iteration terms for grade and courses, fix applied below

### ISSUE THREAD

**Issue by jbok4** [learn-co-curriculum/sinatra-nested-forms-readme#5]
THE DISPLAY VIEW
We need a way to display the objects back to the user (in this case the registrar) once the student and their courses have been created. For later use in the controller, we'll call this file student.erb.

<h1>Student</h1>
 

<div class="student">
  <h3>Name: <%= @student.name %></h3><br>
  <h4>Grade: <%= @student.grade %></h4>
</div><br>

<h1>Courses</h1>

<% @courses.each do |class| %>
  <div class="class">
    <p>Name: <%= class.name %></p><br>
    <p>Type: <%= class.topic %></p><br>
  </div><br>
<% end %>
In this view, we use the instance variable @student and the reader methods .name and .grade to display the student's information.
We then iterate over @courses to display the name and topic of each class.

**Comment by AnnJohn** [comment]
hi @jbok4 could you make a pull request with your suggested fix/edit? thanks.

**Comment by jbok4** [comment]
hi Ann,

Pull request made.
https://github.com/jbok4/sinatra-nested-forms-readme

**Comment by gj** [comment]
Fixed in #12 and #17. Thanks @jbok4 !
